project_name: timelinize
builds:
  -
    id: "timelinize"
    binary: "timelinize"
    dir: .
    env:
      - CGO_ENABLED=1
archives:
  -
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
nfpms:
  -
    vendor:  Matt Holt
    homepage: https://matt.life/
    maintainer: Matt Holt <changeme@example.com>
    description: NA
    license: Private
    formats:
        - apk
        - deb
        - rpm
        - termux.deb
        - archlinux
    release: "1"
    section: default
    priority: extra
